### ISSUE TITLE
The code for extracting character attributes

### ISSUE THREAD

**Issue by zmd971202** [jerrynlp/AutoSum#1]
Hi,
Thank you for your work. Could you please release the code for extracting character attributes?

**Comment by nlprunner** [comment]
Hi,

The function is https://github.com/jerrynlp/AutoSum/blob/master/tools/Syntax.py#L118, which is tested in https://github.com/jerrynlp/AutoSum/blob/master/tools/TestSyntax.ipynb.

Hope it helps.

Thanks,
Weiwei

**Comment by zmd971202** [comment]
Thank you very much!
